version: '3.9'

services:

  redis:
    container_name: bot-redis
    image: redis:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    networks:
      - custom

  mongo:
    container_name: bot-mongo
    image: mongo:latest
    restart: on-failure
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - custom

  bot:
    container_name: bot
    build: .
    command: sh -c "python3 run.py"
    restart: always
    env_file: .env
    depends_on:
      - redis
      - mongo
    networks:
      - custom


networks:

  custom:
    driver: bridge
