version: '3.9'

services:

  redis:
    container_name: redis-bot
    image: redis:latest
    restart: on-failure
    command:
      - redis-server
    env_file:
      - .env
    ports:
      - ${REDISPORT}:${REDISPORT}
    expose:
      - ${REDISPORT}
    volumes:
      - /usr/src/app/data:/bitnami/redis/data


  postgres:
    container_name: postgres-bot
    image: postgres:15-alpine
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDB}
    ports:
        - ${PGPORT}:${PGPORT}
    expose:
        - ${PGPORT}
    volumes:
      - /usr/src/app/data:/var/lib/postgresql/data/pgdata

  bot:
    container_name: bot
    build: .
    command: sh -c "python3 run.py"
    restart: on-failure
    env_file: ./.env
    depends_on:
      - redis
      - postgres


volumes:
  postgres-data:
  redis-data: